name: Deploy GamanAPI to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16.0' # Update if you're using a different version

      - name: Install dependencies
        run: npm install

      - name: Test API
        run: npm test # Remove this step if you don't have tests yet

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a gamanapi
          git push heroku main
